### ISSUE TITLE
Q (process noise covariance matrix) not used in prediction

### ISSUE THREAD

**Issue by willemvdg** [itamarwe/kalman#5]
In the KalmanModel.update() Predict part, the calculation for P (P = FPF(T) + Q) misses the Q part (which is not used anywhere else). 
I think
`this.P_k_k_ = this.F_k.x(this.P_k_.x(this.F_k.transpose()));`
should be
`this.P_k_k_ = this.F_k.x(this.P_k_.x(this.F_k.transpose())).add(this.Q_k);`

In my tests this modification fixed the problem that new measurements did not really have much effect.

**Comment by itamarwe** [comment]
Indeed, it seems like it was missing.
I fixed it at 34caf1d6e0b4d777f41a51e1aa4705f902edaae5
Also, I noticed that the initialization of the observation model was not done correctly, and fixed it at 065e650cad4d8731163ea2cc553079a4db160aa2

Did that solve your problem?

**Comment by willemvdg** [comment]
Thanks for the quick update. The initialization issue was mentioned earlier by @imp-guru (and by having "use strict";).
Need to test more but it looks promising.
